drivers: Add missing fingerprint sensor pose config
kernel/motorola/sm7250/drivers/input/fingerprint/ets_fps_mmi/ets_navi_input.c:96:5: error: 'CONFIG_INPUT_EGISTEC_FPS_POSE' is not defined, evaluates t
o 0 [-Werror,-Wundef]
   96 | #if CONFIG_INPUT_EGISTEC_FPS_POSE==0
      |     ^

Commit d302bf0ccad18106cb29e3f9ad4381e47183c00d is useless without this.

Signed-off-by: Pranav Vashi <neobuddy89@gmail.com>